### ISSUE TITLE
Uncaught TypeError: this.setData is not a function

### ISSUE THREAD

**Issue by reckerswartz** [mtuck063/ajax-autocomplete#1]
working with materialize css for auto complete ajax, data is show in console but with error this.setData is not a function

`$('.ajax-autocomplete').autocomplete({
    theme : 'materialize',
          callback : function(value){
           $.ajax({ 
             url:"/areasearch",
             method: "POST",
             dataType: "JSON",
             data: {city: $("#search").val()},
           success: function(data){ 
		  console.log(data);
                 this.setData(data);
              }  
            }) 
          }
  })`

Any help will be Welcomed

**Comment by mtuck063** [comment]
To have access to 'this' you must bind it to your success function:

```js
$('.ajax-autocomplete').autocomplete({ theme : 'materialize', callback : function(value){ 
  $.ajax({ url:"/areasearch", method: "POST", dataType: "JSON", data: {city: $("#search").val()},
    success: function(data){
      console.log(data); 
      this.setData(data); 
    }.bind(this) 
  }) 
}})
```

**Comment by ReckerSwartz** [comment]
Thanks Bro you just made my day.

**Comment by ReckerSwartz** [comment]
Hey @mtuck063  I'm Working with RoR with turbolinks . autocomplete-ajax is in script tag but only works when i refresh the page not after navigation. Do you any idea how to solve this?
thanks in advance.

**Comment by mtuck063** [comment]
Put your code in this:

```js
$(document).on('page:change', function(){
  ...
}
```

**Comment by ReckerSwartz** [comment]
not working I am on rails 5 with Turbolinks 5 
where there is no option of 
$(document).on('page:change', function(){
  ...
}
